from __future__ import annotations
# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# fmt: off
# -- template metadata.py.jinja --


PRISMA_MODELS: set[str] = {
    'CallLog',
    'User',
    'Session',
    'Account',
    'VerificationToken',
}

RELATIONAL_FIELD_MAPPINGS: dict[str, dict[str, str]] = {
    'CallLog': {
    },
    'User': {
        'sessions': 'Session',
        'accounts': 'Account',
    },
    'Session': {
        'user': 'User',
    },
    'Account': {
        'user': 'User',
    },
    'VerificationToken': {
    },
}

# fmt: on