// File: app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// 1. --- REMOVE THE AUTHPROVIDER IMPORT ---

const inter = Inter({ subsets: ["latin"] });

export const metadata: {
  title: string;
  description: string;
} = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        {/* 2. --- REMOVE THE WRAPPER --- */}
        {children}
      </body>
    </html>
  );
}